### PR TITLE
PR for #60

### PR DESCRIPTION
**Pull request by firefoxNX**

### CODE REVIEW

**Comment by firefoxNX** [comment]
changed node version in Dockefile

**Comment by firefoxNX** [comment]
@kr1sp1n running tests locally code coverage is 100%. Any idea whats going on when run from coveralls?

**Comment by kr1sp1n** [comment]
@firefoxNX Please merge with the latest `master`. Thanks!

**Comment by kr1sp1n** [comment]
@firefoxNX Btw, some changes in your PR like code formatting should not be part of it. I would prefer a separate PR for stuff like this, ok?

**Comment by firefoxNX** [comment]
sure will open another PR

**Pull request closed without merging**
