### PR TITLE
adding gcp login to auth types

### PR DESCRIPTION
**Pull request by saranrapjs**
I've added the Google Cloud login as a supported auth type, per the API documentation here:

https://www.vaultproject.io/api/auth/gcp/index.html#login

Let me know if there's anything else I should add/amend!

### CODE REVIEW

**Comment by saranrapjs** [comment]
(I also ran into the `api.nodesecurity.io` error that Travis is reporting locally, had assumed it was something in my network topology, but perhaps not)

**Comment by kr1sp1n** [comment]
Hi @saranrapjs, my PR #111 fixed the test setup 🎉
Could you please merge the latest changes from `master`? Thanks 🙏

**Comment by saranrapjs** [comment]
@kr1sp1n done!

**Comment by kr1sp1n** [comment]
@saranrapjs Merged and published as v0.9.6 on npm 🎉

**Pull request merged**
