### PR TITLE
Simplified tooling

### PR DESCRIPTION
**Pull request by fearphage**
I did a few things here:

* replaced the `gulp` wrappers with the native tools --  It makes things run a little faster and it feels a little more straightforward. 
* made `npm test` only run tests
* added `coverage` and `lint` targets for `npm run` -- `npm run coverage` is exactly what `npm test` used to be.

Let me know what you think.

Note: You didn't check in the latest/most up to date version of `features.md`. I noticed changes when I ran `npm run docs` (and `gulp docs`).

### CODE REVIEW

**Comment by fearphage** [comment]
I included `--include-all-sources` in the call to istanbul since it seems to be equivalent to the `includeUntested: true` setting in the `gulp-istanbul` plugin. However, the plugin seemingly didn't work before. I can remove that flag to ignore all these other files.

**Comment by kr1sp1n** [comment]
@fearphage Would love to merge your PR. Can you please merge the latest changes from `master`? Thanks!

**Comment by julianbei** [comment]
Should we get this done somehow? I could intervene this week.

**Comment by kr1sp1n** [comment]
@fearphage Thank you so much 🙏

**Pull request merged**
