### PR TITLE
feat(vault-namespace): set 'X-Vault-Namespace' when a client has it

### PR DESCRIPTION
**Pull request by kakoc**
related issue #123

### CODE REVIEW

**Comment by Pluies** [comment]
Hi @kr1sp1n 👋 
Would it be possible to look into merging this feature? I understand that it's a very specific Entreprise-only (AFAIK) Vault feature, but having support would be hugely useful for us as well.
Thank you!
- Florent

**Comment by Pluies** [comment]
FWIW I've [forked node-vault](https://github.com/Pluies/node-vault), applied @kakoc 's patch and published the package under a personal NPM repo ([@florentdelannoyynap/node-vault](https://www.npmjs.com/package/@florentdelannoyynap/node-vault)) and I can report everything is working beautifully!

**Comment by ChamNouki** [comment]
If i well understand how this package work, following code should do the same thing than this PR :
```typescript
const vaultOptions: VaultOptions = {
  requestOptions: {
    headers: {
      'X-Vault-Namespace': process.env.VAULT_NAMESPACE
    }
  }
};

const vault = Vault(vaultOptions);
```
However I still have an error but this time it's a 404.

**Comment by kr1sp1n** [comment]
@kakoc Thanks for your PR 👍
@Pluies Released as [v0.9.18](https://www.npmjs.com/package/node-vault/v/0.9.18) 🎉
Closes #123

**Pull request merged**
