### PR TITLE
fixed coveralls implementation

### PR DESCRIPTION
**Pull request by fearphage**
I'm not sure what's up with codecov, but I fixed coveralls. :man_shrugging:

### CODE REVIEW

**Comment by kr1sp1n** [comment]
@fearphage Would use only codecov for now. Any concerns? If not I need to find out how to disable coveralls on github 😄

**Comment by julianbei** [comment]
Give me a shout as soon as you are in the office. I gonna help you there. Had that kind of problem yesterday!

**Comment by fearphage** [comment]
Do you still need anything from me?

**Comment by kr1sp1n** [comment]
@fearphage I tried to get rid of coveralls but I can not delete it from the github checks. I am a little bit lost here. I would love to not go back to coveralls but maybe I should to have a cleaner environment. WDYT?

**Comment by fearphage** [comment]
I believe one way to fix this is by going to the coveralls site. There you should be able to unlink it from this project/repository. I haven't used it though so I can't say for sure.

**Comment by kr1sp1n** [comment]
@fearphage It was a special setting in Github to disable coveralls. So we will keep using codecov for now. Nevertheless thanks for your effort 🙏

**Pull request closed without merging**
