### PR TITLE
Improve consistency of handling methods that generate tokenResponse objects

### PR DESCRIPTION
**Pull request by owenfarrell**
Following up on #93, there are a handful of methods that generate a tokenResponse object but were not marked as `tokenSource` methods.

Selfishly, I'm interested in `/auth/token/renew-self`. But I'm guessing there are others in the community who are interested in the other methods as well.

### CODE REVIEW

**Comment by kr1sp1n** [comment]
@owenfarrell Please merge the latest changes from `master`.

**Comment by owenfarrell** [comment]
@kr1sp1n Just rebased my fork over the commits upstream. Let me know if you need anything else.

**Comment by kr1sp1n** [comment]
@owenfarrell Finally released your changes as v0.9.14 -> https://www.npmjs.com/package/node-vault/v/0.9.14 🎉 
Sorry for the very late reply and thanks for your PR 🙏

**Comment by Kamahl19** [comment]
@kr1sp1n whats the point of setting renew-self as token source? Token is not being changed in this case, so we shouldnt override it, right?

**Comment by owenfarrell** [comment]
@Kamahl19 - you raise a good point. In theory that shouldn't have any effect on the cached token (it should replace the value with an identical value).

When I wrote this, my thought was to set the `tokenSource` attribute on any method that returns a token. And [renew-self](https://www.vaultproject.io/api-docs/auth/token/#renew-a-token-self) does just that.

It also serves as a bit of defensive programming in the event that (1) Vault changes their mind at some point and "renew" turns in to more of a "rotate" or (2) node-vault wants to cache the whole token object (just the `client_token` string), including lease duration, metadata, and policies.

**Pull request merged**
