### PR TITLE
added namespace to VaultOptions

### PR DESCRIPTION
**Pull request by kstiehl**
A minor change but this way an IDE shows directly that it can be configured instead of having to look into the source code.
so this is the outcome.

### CODE REVIEW

**Comment by owenfarrell** [comment]
Related to #154

**Comment by kstiehl** [comment]
@owenfarrell  thnx 👍

**Comment by owenfarrell** [comment]
@kstiehl - Sorry, I should've been more clear. I think this change is related to the changes I've proposed in #154... but #154 doesn't include this particular attribute.

My goal was to raise awareness for @kr1sp1n that there is an opportunity to review 2 related changes at the same time.

**Comment by kr1sp1n** [comment]
@owenfarrell Thanks for raising awareness and the related PR 😉
@kstiehl Thanks for this PR 🙏
I will release a new version of the package.

**Comment by kr1sp1n** [comment]
@owenfarrell @kstiehl both PRs are now released as [v0.9.19](https://www.npmjs.com/package/node-vault/v/0.9.19) 🎉

**Comment by kstiehl** [comment]
@owenfarrell oh thnx for pointing that out. Was a bit busy so I didn't check the code from your PR.

@kr1sp1n Thnx for quick merging and releasing.

Nice work guys

Cheers  🍻

**Pull request merged**
