### PR TITLE
kubernetesLogin: make it a token source

### PR DESCRIPTION
**Pull request by mpareja**
This PR builds on the work to add kubernetes login support (#92) and the ability to enable some commands to update client tokens (#93). This PR enables updating client tokens as part of the kubernetesLogin command.

### CODE REVIEW

**Comment by kr1sp1n** [comment]
Hi @mpareja my PR #111 fixed the test setup 🎉
Could you please merge the latest changes from `master`? Thanks 🙏

**Comment by mpareja** [comment]
Hi @kr1sp1n,

I rebased and force-pushed this branch to bring up to date with master.

Cheers!

**Comment by kr1sp1n** [comment]
@mpareja Please rebase and push again. Sorry, you are the next 😉

**Comment by mpareja** [comment]
Done. Awaiting Travis tests.

**Comment by kr1sp1n** [comment]
Ok, merged and published as v0.9.7 🎉

**Pull request merged**
